CREATE TABLE `USERS` (
	`id`	int	NOT NULL,
	`username`	varchar(255)	NOT NULL,
	`hashed_password`	varchar(255)	NOT NULL,
	`email`	varchar(255)	NOT NULL,
	`secret_key`	varchar(255)	NULL,
	`gender`	varchar(255)	NULL,
	`type_name`	varchar(255)	NULL
);

CREATE TABLE `REVIEWS` (
	`suppliment_id`	int	NOT NULL,
	`id`	int	NOT NULL,
	`rating`	tinyint	NOT NULL,
	`text`	text	NULL,
	`registration_day`	date	NOT NULL
);

CREATE TABLE `SUPPLEMENTS` (
	`id`	int	NOT NULL,
	`product_name`	varchar(255)	NOT NULL,
	`company_name`	varchar(255)	NULL,
	`avg_rating`	float	NULL
);

CREATE TABLE `TYPES` (
	`name`	varchar(255)	NULL
);

CREATE TABLE `SUPPLEMENT_TAGS` (
	`supplement_id`	int	NOT NULL,
	`tag_name`	varchar(255)	NOT NULL
);

CREATE TABLE `WISHLIST` (
	`id`	int	NOT NULL,
	`suppliment_id`	int	NOT NULL
);

CREATE TABLE `REVIEW_IMGS` (
	`img_url`	varchar(255)	NULL,
	`suppliment_id`	int	NOT NULL,
	`id`	int	NOT NULL
);

CREATE TABLE `INGREDIENTS` (
	`id`	int	NOT NULL,
	`name`	varchar(255)	NOT NULL
);

CREATE TABLE `TEMP_PW` (
	`id`	int	NOT NULL,
	`temp_password`	varchar(255)	NOT NULL
);

CREATE TABLE `SUPPLEMENT_INGREDIENT` (
	`supplement_id`	int	NOT NULL,
	`ingredient_id`	int	NOT NULL
);

CREATE TABLE `TYPE_TAG` (
	`type_name`	varchar(255)	NULL,
	`tag_name`	varchar(255)	NOT NULL
);

CREATE TABLE `TAGS` (
	`name`	varchar(255)	NOT NULL
);

ALTER TABLE `USERS` ADD CONSTRAINT `PK_USERS` PRIMARY KEY (
	`id`
);

ALTER TABLE `USERS` MODIFY id INT AUTO_INCREMENT;

ALTER TABLE `REVIEWS` ADD CONSTRAINT `PK_REVIEWS` PRIMARY KEY (
	`suppliment_id`,
	`id`
);

ALTER TABLE `SUPPLEMENTS` ADD CONSTRAINT `PK_SUPPLEMENTS` PRIMARY KEY (
	`id`
);

ALTER TABLE `SUPPLEMENTS` MODIFY id INT AUTO_INCREMENT;

ALTER TABLE `TYPES` ADD CONSTRAINT `PK_TYPES` PRIMARY KEY (
	`name`
);

ALTER TABLE `SUPPLEMENT_TAGS` ADD CONSTRAINT `PK_SUPPLEMENT_TAGS` PRIMARY KEY (
	`supplement_id`,
	`tag_name`
);

ALTER TABLE `WISHLIST` ADD CONSTRAINT `PK_WISHLIST` PRIMARY KEY (
	`id`,
	`suppliment_id`
);

ALTER TABLE `REVIEW_IMGS` ADD CONSTRAINT `PK_REVIEW_IMGS` PRIMARY KEY (
	`img_url`,
	`suppliment_id`,
	`id`
);

ALTER TABLE `INGREDIENTS` ADD CONSTRAINT `PK_INGREDIENTS` PRIMARY KEY (
	`id`
);

ALTER TABLE `INGREDIENTS` MODIFY id INT AUTO_INCREMENT;

ALTER TABLE `TEMP_PW` ADD CONSTRAINT `PK_TEMP_PW` PRIMARY KEY (
	`id`
);

ALTER TABLE `SUPPLEMENT_INGREDIENT` ADD CONSTRAINT `PK_SUPPLEMENT_INGREDIENT` PRIMARY KEY (
	`supplement_id`,
	`ingredient_id`
);

ALTER TABLE `TYPE_TAG` ADD CONSTRAINT `PK_TYPE_TAG` PRIMARY KEY (
	`type_name`,
	`tag_name`
);

ALTER TABLE `TAGS` ADD CONSTRAINT `PK_TAGS` PRIMARY KEY (
	`name`
);

ALTER TABLE `USERS` ADD CONSTRAINT `FK_TYPES_TO_USERS_1` FOREIGN KEY (
	`type_name`
)
REFERENCES `TYPES` (
	`name`
);

ALTER TABLE `REVIEWS` ADD CONSTRAINT `FK_SUPPLEMENTS_TO_REVIEWS_1` FOREIGN KEY (
	`suppliment_id`
)
REFERENCES `SUPPLEMENTS` (
	`id`
);

ALTER TABLE `REVIEWS` ADD CONSTRAINT `FK_USERS_TO_REVIEWS_1` FOREIGN KEY (
	`id`
)
REFERENCES `USERS` (
	`id`
);

ALTER TABLE `SUPPLEMENT_TAGS` ADD CONSTRAINT `FK_SUPPLEMENTS_TO_SUPPLEMENT_TAGS_1` FOREIGN KEY (
	`supplement_id`
)
REFERENCES `SUPPLEMENTS` (
	`id`
);

ALTER TABLE `SUPPLEMENT_TAGS` ADD CONSTRAINT `FK_TAGS_TO_SUPPLEMENT_TAGS_1` FOREIGN KEY (
	`tag_name`
)
REFERENCES `TAGS` (
	`name`
);

ALTER TABLE `WISHLIST` ADD CONSTRAINT `FK_USERS_TO_WISHLIST_1` FOREIGN KEY (
	`id`
)
REFERENCES `USERS` (
	`id`
);

ALTER TABLE `WISHLIST` ADD CONSTRAINT `FK_SUPPLEMENTS_TO_WISHLIST_1` FOREIGN KEY (
	`suppliment_id`
)
REFERENCES `SUPPLEMENTS` (
	`id`
);

ALTER TABLE `REVIEW_IMGS` ADD CONSTRAINT `FK_REVIEWS_TO_REVIEW_IMGS_1` FOREIGN KEY (
	`suppliment_id`
)
REFERENCES `REVIEWS` (
	`suppliment_id`
);

ALTER TABLE `REVIEW_IMGS` ADD CONSTRAINT `FK_REVIEWS_TO_REVIEW_IMGS_2` FOREIGN KEY (
	`id`
)
REFERENCES `REVIEWS` (
	`id`
);

ALTER TABLE `TEMP_PW` ADD CONSTRAINT `FK_USERS_TO_TEMP_PW_1` FOREIGN KEY (
	`id`
)
REFERENCES `USERS` (
	`id`
);

ALTER TABLE `SUPPLEMENT_INGREDIENT` ADD CONSTRAINT `FK_SUPPLEMENTS_TO_SUPPLEMENT_INGREDIENT_1` FOREIGN KEY (
	`supplement_id`
)
REFERENCES `SUPPLEMENTS` (
	`id`
);

ALTER TABLE `SUPPLEMENT_INGREDIENT` ADD CONSTRAINT `FK_INGREDIENTS_TO_SUPPLEMENT_INGREDIENT_1` FOREIGN KEY (
	`ingredient_id`
)
REFERENCES `INGREDIENTS` (
	`id`
);

ALTER TABLE `TYPE_TAG` ADD CONSTRAINT `FK_TYPES_TO_TYPE_TAG_1` FOREIGN KEY (
	`type_name`
)
REFERENCES `TYPES` (
	`name`
);

ALTER TABLE `TYPE_TAG` ADD CONSTRAINT `FK_TAGS_TO_TYPE_TAG_1` FOREIGN KEY (
	`tag_name`
)
REFERENCES `TAGS` (
	`name`
);


